server:
  port: 8083

spring:
  application:
    name: users-service
  datasource:
    url: jdbc:mysql://localhost:3307/digital_money_house
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/digital-money-house

keycloak:
    admin:
      client-id: digital-money-house-client
      client-secret: ${KEYCLOAK_CLIENT_SECRET}
      realm: digital-money-house
      server-url: http://localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/