server:
  port: 8081

spring:
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: digital-money-house-client
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: password
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/digital-money-house
            token-uri: http://localhost:8082/realms/digital-money-house/protocol/openid-connect/token

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/